name: Build and Release SAM PRO Desktop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create version info
      run: |
        $version = "${{ github.event.inputs.version || github.ref_name }}"
        $version = $version -replace '^v', ''
        $versionParts = $version -split '\.'
        while ($versionParts.Length -lt 4) { $versionParts += '0' }
        $fileVersion = $versionParts -join ','
        
        $versionInfo = @"
        # UTF-8
        VSVersionInfo(
          ffi=FixedFileInfo(
            filevers=($fileVersion),
            prodvers=($fileVersion),
            mask=0x3f,
            flags=0x0,
            OS=0x4,
            fileType=0x1,
            subtype=0x0,
            date=(0, 0)
            ),
          kids=[
            StringFileInfo(
              [
              StringTable(
                u'040904B0',
                [StringStruct(u'CompanyName', u'SAM PRO'),
                StringStruct(u'FileDescription', u'SAM PRO - نظام إدارة المبيعات والمخزون'),
                StringStruct(u'FileVersion', u'$version'),
                StringStruct(u'InternalName', u'SAM_PRO'),
                StringStruct(u'LegalCopyright', u'© 2024 SAM PRO. All rights reserved.'),
                StringStruct(u'OriginalFilename', u'SAM_PRO.exe'),
                StringStruct(u'ProductName', u'SAM PRO - Sales and Inventory Management System'),
                StringStruct(u'ProductVersion', u'$version')])
              ]), 
            VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
          ]
        )
        "@
        
        $versionInfo | Out-File -FilePath "version_info.txt" -Encoding UTF8
        
    - name: Build executable
      run: |
        echo "Building SAM PRO Desktop Application..."
        pyinstaller sam_pro.spec
        
    - name: Verify build
      run: |
        if (Test-Path "dist\SAM_PRO.exe") {
          echo "✅ Build successful! Executable created."
          $size = (Get-Item "dist\SAM_PRO.exe").Length
          echo "📦 File size: $([math]::Round($size/1MB, 2)) MB"
        } else {
          echo "❌ Build failed! Executable not found."
          exit 1
        }
        
    - name: Create portable package
      run: |
        $version = "${{ github.event.inputs.version || github.ref_name }}"
        $packageName = "SAM_PRO_Desktop_$version"
        
        # Create package directory
        New-Item -ItemType Directory -Path $packageName -Force
        
        # Copy executable
        Copy-Item "dist\SAM_PRO.exe" "$packageName\"
        
        # Create README
        $readme = @"
        # SAM PRO Desktop - نظام إدارة المبيعات والمخزون
        
        ## تعليمات التشغيل
        
        1. قم بتشغيل ملف SAM_PRO.exe
        2. انقر على "تشغيل الخادم" لبدء التطبيق
        3. انقر على "فتح التطبيق" لفتح واجهة الويب
        4. استخدم التطبيق من خلال المتصفح
        
        ## المتطلبات
        - Windows 10 أو أحدث
        - لا حاجة لتثبيت Python أو أي متطلبات إضافية
        
        ## الدعم الفني
        للحصول على المساعدة، يرجى زيارة:
        https://github.com/mohazard555/sam-pro-desktop/issues
        
        ## الإصدار
        $version
        
        تاريخ البناء: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        "@
        
        $readme | Out-File -FilePath "$packageName\README.txt" -Encoding UTF8
        
        # Create ZIP package
        Compress-Archive -Path $packageName -DestinationPath "$packageName.zip"
        
        echo "📦 Package created: $packageName.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SAM_PRO_Desktop_${{ github.event.inputs.version || github.ref_name }}
        path: |
          dist/SAM_PRO.exe
          SAM_PRO_Desktop_*.zip
          
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: SAM PRO Desktop ${{ github.event.inputs.version || github.ref_name }}
        body: |
          # SAM PRO Desktop - نظام إدارة المبيعات والمخزون
          
          ## ما الجديد في هذا الإصدار
          - تطبيق سطح مكتب كامل الميزات
          - واجهة مستخدم سهلة الاستخدام
          - لا حاجة لتثبيت Python
          - يعمل بدون اتصال بالإنترنت
          
          ## كيفية التثبيت والاستخدام
          1. قم بتحميل ملف `SAM_PRO_Desktop_*.zip`
          2. استخرج الملفات إلى مجلد على جهازك
          3. قم بتشغيل `SAM_PRO.exe`
          4. اتبع التعليمات في التطبيق
          
          ## متطلبات النظام
          - Windows 10 أو أحدث
          - 4 جيجابايت رام (الحد الأدنى)
          - 500 ميجابايت مساحة فارغة
          
          ## الملفات المتاحة
          - `SAM_PRO.exe` - الملف التنفيذي المفرد
          - `SAM_PRO_Desktop_*.zip` - الحزمة الكاملة مع التعليمات
          
          ---
          
          **تاريخ الإصدار:** $(date +'%Y-%m-%d')
          **حجم التطبيق:** ~50-100 MB
        files: |
          dist/SAM_PRO.exe
          SAM_PRO_Desktop_*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
