name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Flask app
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        try:
            from app import create_app
            app = create_app()
            print('✅ Flask app imports successfully')
        except Exception as e:
            print(f'❌ Flask app import failed: {e}')
            sys.exit(1)
        "
        
    - name: Test main.py
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        try:
            import main
            print('✅ Main module imports successfully')
        except Exception as e:
            print(f'❌ Main module import failed: {e}')
            sys.exit(1)
        "
        
    - name: Test build (dry run)
      run: |
        echo "Testing PyInstaller spec file..."
        pyinstaller --noconfirm --log-level=DEBUG sam_pro.spec --distpath test_dist --workpath test_build
        
    - name: Verify test build
      run: |
        if (Test-Path "test_dist\SAM_PRO.exe") {
          echo "✅ Test build successful!"
          $size = (Get-Item "test_dist\SAM_PRO.exe").Length
          echo "📦 Test executable size: $([math]::Round($size/1MB, 2)) MB"
        } else {
          echo "❌ Test build failed!"
          Get-ChildItem test_build -Recurse | Where-Object { $_.Name -like "*.log" } | ForEach-Object { 
            echo "=== $($_.Name) ==="
            Get-Content $_.FullName -Tail 50
          }
          exit 1
        }
        
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-build-logs
        path: |
          test_build/
          test_dist/
